In [1]:
import numpy as np

Write a command to create the below array using NumPy. 
 Call this array a: array([[ 3, 2, 1, 0], [ 7, 6, 5, 4], [11, 10, 9, 8]])

In [2]:
a = np.array([[3, 2, 1, 0], [7, 6, 5, 4], [11, 10, 9, 8]])
print(a)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]


How would you fetch the shape of the array?

In [3]:
print(a.shape)

(3, 4)


Numpy provides a function to create an array full of zeros. Write a line of code which
creates such an array of dimensions 50 x 50.

In [5]:
z = np.zeros((50,50))
print(z)
print(z.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(50, 50)


Numpy provides a function to create a sequence of numbers. Write the code to create an array which consists of numbers from 0 to 11 (inclusive) arranged in 3 rows and 4 columns. Call this array b.

In [7]:
b = np.arange(12)
b = b.reshape(3,4)

print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


The operator * performs element-wise multiplication in NumPy arrays. Perform the
operation (a * b) and report the resulting matrix.

In [8]:
print(a*b)

[[ 0  2  2  0]
 [28 30 30 28]
 [88 90 90 88]]


Write code to perform matrix multiplication of NumPy arrays (the * operator per-
forms element-wise multiplication). Use arrays a and the transpose of a to perform
this operation. Hint: (.T) operator can be used to perform a transpose.

In [9]:
print(np.matmul(a,a.T))

[[ 14  38  62]
 [ 38 126 214]
 [ 62 214 366]]


Indexing and Slicing

(a) Write a line of code to print the 2nd element of 3rd row in array a

In [18]:
print(a[2,1:2])

[10]


(b) Write a line of code to print only the 2nd row of array b

In [19]:
print(b[1,:])

[4 5 6 7]


(c) Assuming you don't know the dimensions of the array, write a line of code to
print the last column of array b.

In [28]:
print(b[:,-1])

[ 3  7 11]


Write a line of code to reshape the array b such that it has 6 rows and 2 columns

In [30]:
b = b.reshape(6,2)
print(b)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


Sorting

(a) Write code to sort array a by rows (Use the sort function provided by NumPy)

In [37]:
print(np.sort(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


(b) How would the result differ if `axis' parameter in the sort function is not specified?

In [41]:
print(np.sort(a, axis=None))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
